### ISSUE TITLE
Have a look and work on the plugin

### ISSUE THREAD

**Issue by baicu4design** [baicu4design/b4dplug#1]
Catalin, can you please have a look and work on the plugin. Thanks

**Comment by catalinbaicu** [comment]
Yes, sure. Will start with it tomorrow morning.

**Comment by baicu4design** [comment]
Thank you :)

**Comment by catalinbaicu** [comment]
Will start tomorrow morning but I wont be able to finish till Wednesday night 20.03.2019

**Comment by baicu4design** [comment]
Yep. That is perfectly fine for me, thank you again :)
